tile-server:
  build: ./tile-server
  links:
    - db
  volumes:
    - /mnt/cache_data:/cache_data

db:
  build: ./db
  volumes:
    - /mnt/db_data:/var/lib/postgresql/data
  environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_DB=tile_db
    - POSTGRES_USER=tile_db

osmtm:
  build: ./osmtm
