tile-server:
  build: ./tile-server
  links:
    - db
  volumes:
    - /cache_data
  ports:
    - "127.0.0.1:8787:8080"

db:
  build: ./db
  volumes:
    - ./db/data:/data
    - /var/lib/postgresql/data
  environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_DB=tile_db
    - POSTGRES_USER=tile_db
